//http://localhost:8080/pipeline-model-converter/validate

pipeline 
{
	agent any
	
	stages 
	{
		stage ('Build')
		{
			steps 
			{
				
				echo 'Build'
			}
		}
		stage ('Test')
		{
			steps { 
				echo 'Test'
				}
		}
	}
}

		

