//http://localhost:8080/pipeline-model-converter/validate

pipeline {
	agent { docker {image "maven:3.6.3"}}
	stages {
		stage ('Build'){
			steps { 
				sh "maven --version"
				echo “Build”
				}
			}
		}

	stages {
		stage (‘Test’){
			steps { 
				echo “Test”
				}
			}
		}
}